title: 물민초's Blog
email: whalstn9@gmail.com
description: 물민초의 개발블로그
author: Start Bootstrap
baseurl: ""
url: "https://watermincho.github.io/"

# Social Profiles
twitter_username: SBootstrap
github_username: WaterMinCho
facebook_username: 조민수
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
